### ISSUE TITLE
Incorrect path to output xml

### ISSUE THREAD

**Issue by Papay** [Wintellect/PowerThreading#1]
When buid Release Configuration has error.
In file: PowerThreading-Silverlight/PowerThreading-Silverlight.csproj
Need change path from: 
"<DocumentationFile>C:\Users\Jeffrey\Documents\Seminars\Threading\Code\PowerThreading\Wintellect.Threading.Silverlight.xml</DocumentationFile>"
To: 
"<DocumentationFile>......\Seminars\Threading\Code\PowerThreading\Wintellect.Threading.Silverlight.xml</DocumentationFile>"

**Comment by KeithJRome** [comment]
I would be happy to merge your fix for this - could you submit a small pull request with the updated file?

**Comment by Papay** [comment]
Unfortunately, I don't have enough rights for push changes to the project Power Threading on Github I can send you the corrected file by e-mail, if you tell me your email.

**Comment by KeithJRome** [comment]
You shouldn't need push rights. If you fork the project and commit your changes to your fork then you can submit the commit in a pull request to the main project. This requires no special access rights since you aren't actually pushing to the main repository. Once we review and accept the pull request then it pulls your code change into the repository.

It is all much easier to do than I'm probably making it sound. You can learn about how the system works here: https://help.github.com/articles/using-pull-requests

This mechanism also allows us to give proper credit to contributors, because the pull request maintains the source lineage. In other words - it will show the change as having come from you and not us.

**Comment by Papay** [comment]
I am send pull request. Can you check it?

**Comment by KeithJRome** [comment]
Yes, I reviewed and accepted it.

Thanks for contributing!
